spring:
  datasource:
    url: jdbc:postgresql://${SUPABASE_HOST}:5432/${SUPABASE_DATABASE}
    driverClassName: org.postgresql.Driver
    username: ${SUPABASE_USERNAME}
    password: ${SUPABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: verySecureSecretKeyForJWTTokenGenerationAndValidation
  expiration: 86400000  # 24 hours

server:
  port: 8080