name: Continuous Integration (CI)

## Run CI jobs on all branches by default
on:
  push:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04

    # Add environment variables section
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      # Optional: Print environment variables to verify (masked in logs)
      - name: Verify environment variables exist
        run: |
          if [ -n "$DB_HOST" ]; then echo "DB_HOST is set"; else echo "DB_HOST is not set"; fi
          if [ -n "$DB_PORT" ]; then echo "DB_PORT is set"; else echo "DB_PORT is not set"; fi
          if [ -n "$DB_NAME" ]; then echo "DB_NAME is set"; else echo "DB_NAME is not set"; fi
          if [ -n "$DB_USER" ]; then echo "DB_USER is set"; else echo "DB_USER is not set"; fi
          if [ -n "$DB_PASSWORD" ]; then echo "DB_PASSWORD is set"; else echo "DB_PASSWORD is not set"; fi

      - name: Run unit tests
        run: ./gradlew test